src/clipboard-action.js, src/clipboard.js, test/clipboard-action.js
Default parameters (introduced in zenorocha/clipboard.js#20) require `undefined` rather than other falsy values. `getAttribute` returns `null`, and we were passing in the empty string to the test.
=> Fix for default parameters (zenorocha/clipboard.js#20)

dist/clipboard.js, src/clipboard-action.js
See only 281 line. On your examples uses input element and textarea, but if you will use manual method of copying you can't copy with line break (\n) because input element does not support line break(\n - this symbol). You should use textarea element instead of input element for support line break.
P.S.: Sorry for WebStorm code reformat.
=> Changed "fakeElem" element type.

package.json
Added the .git and the dist/ directories to the .gitignore file
Added "build-watch" command based on watchify (https://github.com/substack/watchify), I've been using this for a while in my projects.
Removed dist/ directory from the cloned code. It can be built locally anyway so there is no use of it (eventually the dist/ folder can be created each time a new version is released)
=> Added "build-watch" command. Added ".git" and "dist" directories to .gitignore

src/clipboard-action.js
In Firefox < 41, the selecting fakeElem.select() would cause the browser to scroll to the bottom of the page. 
By positioning fakeElem at the current scroll position, but still way out to the left, that no longer happens.
=> Prevent FF < 41 scrolling to bottom of  page

src/clipboard-action.js
My previous fix didn't actually work. Instead of scrolling to the bottom it would scroll to the top, because it turns out document.body.scrollTop always returns 0 in Firefox.
This should work in most browsers.
See here: http://help.dottoro.com/ljnvjiow.php
Sorry for submitting a broken fix. I thought I'd tested it, but not well enough clearly.
=> Fix for scrolling to top in unsupported firefox

.travis.yml, package.json
UglifyJS 1 fails on NPM 3 since it needs grunt explicitly defined as dependency.
So, following #69 stats.
UglifyJS 1
```shell
$ gzipped dist/clipboard.min.js                  
Original size: 7.67 kB
Compressed size: 2.61 kB
Compression ratio: 33.99%
```
UglifyJS 2 (with mangle and screw ie8 option)
```shell
$ gzipped dist/clipboard.min.js
Original size: 7.70 kB
Compressed size: 2.60 kB
Compression ratio: 33.73%
```
=> fix npm3 build updating uglifyjs to version 2

src/clipboard.js, test/clipboard.js
Updated `onClick` to use an event's `currentTarget` instead of `target` as this leads to errors when `target` and `currentTarget` are not the same (i.e. the event has already bubbled up).
Pull request in reference to https://github.com/zenorocha/clipboard.js/issues/119
EDIT: CI seems to be failing due to installation issues, tests pass locally.
=> use event's currentTarget instead of target

src/clipboard-action.js
Prevent auto-zooming on an iPhone by making the text area font appropriate size. Fixes Issue #180.
=> Prevent auto-zooming on an iphone 

src/clipboard-action.js
after call clipboard all page scrolls down. As i understand, its relates to fake element, cause its append to body.
I just set position to 'fixed' and now it works right. I think 'fixed' is more css-style independence then 'absolute'
=> minor fix for fake elem

src/clipboard-action.js
addEventListener always returns undefined by spec
https://www.w3.org/TR/DOM-Level-2-Events/events.html#Events-EventTarget-addEventListener
=> Fix memory leak because of fakeHandlers

readme.md
As Safari users are mostly using mac, coping a text needs Command+C instead of Ctrl+C
=> Press Ctrl+C to copy -> Press Command+C to copy

readme.md
Ref: https://github.com/zenorocha/clipboard.js/pull/267#issuecomment-249620994
--
Note: The `Edge` logo will be added by #315.
=> Add `Edge` to the `Browser Support` section from the `README.md`

assets/styles/main.css
Currently, navigating just with the keyboard (TAB/SHIFT+TAB), the snippet buttons remain invisible. This forces the same change of opacity as hovering over the snippet with the mouse.
=> Make snippet buttons appear on kbd focus

src/clipboard-action.js
`blur()` results in a loss/reset of keyboard focus, meaning keyboard users usually get thrown right back to the start of the page. Instead, this moves focus back to the trigger (which had the focus when the trigger was activated).
As with the proposed fix in https://github.com/zenorocha/clipboard.js/pull/418 this obviously results in the focus styles (like the default outline, unless suppressed) being applied to the trigger (see the related PR for rationale and future fix using `:focus-ring`)
=> Move focus to trigger instead of simply blur()ing

package.json
Clipboard.js doesn't support ESM, its package.json shouldn't claim it does.
Reference: https://github.com/rollup/rollup/wiki/pkg.module
=> Don't claim to support ESM

.babelrc, package-lock.json, package.json
Two changes in this PR
- `babel-cli` is not used so that dev-dependency can be dropped
- Since code is uglified using UglifyJS, it's better to make that explicit in the browser config instead of relying on browserslist not to change its behaviour
=> Drop dependency on babel-cli and streamline babel config

readme.md
There was a deprecated link to the Github Primer Tooltips documenation in the repo's readme file.
=> Update broken link to Primer Tooltops doc

src/clipboard-action.js, test/clipboard-action.js
Closes Issue #732 
If adding a **new feature**, the PR's description includes:
=> removing element after selection

webpack.config.js
If adding a **new feature**, the PR's description includes:
This PR should close #737 #738,
what happened was that once we update to use webpack5 the target option was not specified and the build was created with arrow functions, breaking the es5 builds, by targeting the build we can avoid that.
https://webpack.js.org/blog/2020-10-10-webpack-5-release/#improved-code-generation
=> feat adding es5 as target for webpack compilation

.github/workflows/test.js.yml
* add `FORCE_COLOR: 2` so that we get colored output
* update to `actions/setup-node@v2`
* fix formatting
If adding a **new feature**, the PR's description includes:
* Please checkout the non-whitespace diff: https://github.com/zenorocha/clipboard.js/pull/752/files?w=1
* The build step seems unneeded since it already runs on `ci`, but maybe it's as a precaution
* The lint step could be a separate workflow assuming there's npm caching, so that it runs only once
* The `test:types` script does not run on CI ATM
=> Update CI config

src/clipboard.d.ts
If adding a **new feature**, the PR's description includes:
Set `options` arg to be optional for the static `copy` method, as there's a default param.
=> Fix type for copy function

src/clipboard.js, test/clipboard.js
This PR reintroduces the behavior that used to be in clipboard.js following https://github.com/zenorocha/clipboard.js/pull/419 but that has since been reverted for some reason. As such, after a clipboard action, focus will remain/be on the trigger element, rather than the body. If applications rely on the focus to be gone/removed from the trigger button, they'll need to adapt to this.
I didn't target v2.x branch because it looks wildly out of date.
I'm not too hot on writing tests, so rather than just removing the check to …
=> Fix #805 don't `blur()` the trigger after a clipboard action
